import React from 'react';
import { makeStyles } from '@material-ui/core/styles';
import FacebookIcon from '@material-ui/icons/Facebook';
import TwitterIcon from '@material-ui/icons/Twitter';
import InstagramIcon from '@material-ui/icons/Instagram';
import LinkedInIcon from '@material-ui/icons/LinkedIn';
import SportsSoccerIcon from '@material-ui/icons/SportsSoccer';

import LocationOnOutlinedIcon from '@material-ui/icons/LocationOnOutlined';

const useStyles = makeStyles(theme => ({
  main:{
    display:'flex',
    flexDirection:'row',
    [theme.breakpoints.down('xs')]: {
      flexDirection:'column',
    },
    padding:'50px',
    backgroundImage:"linear-gradient(to right, #1F2434 ,	#44527F)",
   
    color:'white'
  },
  image:{
    borderRadius:'50%',
    height:'10rem',
    width:'10rem',
    backgroundSize:'cover',
    marginRight:'2.5rem',
    marginLeft:'5rem',
    transform: "scaleX(-1)",
    [theme.breakpoints.down('xs')]: {
      height:'20rem',
      width:'20rem',
      borderRadius:'50%',
      marginBottom:'2rem'
    },
  },

  image__box:{
    textAlign:'Center',
  },
  carchs:{
    flexBasis:'40%',

    [theme.breakpoints.down('md')]: {
      flexBasis:'50%',
    },
    [theme.breakpoints.down('sm')]: {
      flexBasis:'55%',
    },


  },


  
  name:{
    fontWeight:'lighter',

  },
  job:{
    fontSize:'1.4rem',
    fontWeight:'100',
  },
  genInfo:{
    display:'flex',
    flexDirection:'row',
  },
  born:{
    marginRight:'2.5rem',
  },
  loc:{
    color:'lightblue',
  },
  intro:{
    lineHeight:'1.7rem',
    color:'grey',
    marginBottom:'3rem'
  },
  icons:{
    marginBottom:'5rem'
  },
  icon:{
    marginRight:'1.5rem',
    textDecoration:'none',
    color:'white',
    [theme.breakpoints.down('xs')]: {
      marginRight:'4rem',
    },
  },
  locIcon:{
    color:'white',
    paddingRight:'.5rem',
   
  },

  
}));

const Header = () => {
    const classes = useStyles();
    return (
      <div className={classes.main} >
        <div className={classes.image__box}>
           <img className={classes.image} src="https://upload.wikimedia.org/wikipedia/commons/7/74/Tom_Cruise_%2834797273596%29.jpg" alt="photo 1"></img>
        </div>
        <div className={classes.carchs}>
          <div className={classes.name}>
            <h1>Thomas Cruise Mapother IV <span className={classes.job} >(Actor,Producer)</span></h1>
          </div>
          <div className={classes.genInfo} >
              <div className={classes.born}>
                 <p><span>Born:</span> <span>july 3,1962 (age 54)</span> </p>
                 <p><span>Nationality:</span> <span>United States</span> </p>
              </div>
              <div className={classes.loc}>
                  <LocationOnOutlinedIcon className={classes.locIcon} ></LocationOnOutlinedIcon>
                  <span>Syracus, New York, U.S.</span>
              </div>
          </div>
          <div>
              <p className={classes.intro}> 
              just wordsA flex container is the box generated by an element with a computed display of flex or inline-flex. In-flow children of a flex container are called flex items and are laid out using the flex layout model.
              </p>  
          </div>
          <div className={classes.icons}>
                <a href="#" className={classes.icon}><FacebookIcon></FacebookIcon></a>
                <a href="#" className={classes.icon}><TwitterIcon></TwitterIcon></a>
                <a href="#" className={classes.icon}><InstagramIcon></InstagramIcon></a>
                <a href="#" className={classes.icon}> <LinkedInIcon></LinkedInIcon></a>
                <a href="#" className={classes.icon}><SportsSoccerIcon></SportsSoccerIcon></a>                
          </div>
        </div>
        
      </div>
    );
  }


export default Header;
